#Modify all lines indicated with MODIFY
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
chromosomes: "22"
outname: "test"
query:
  cog1: "/Users/pmonnaha/Documents/Research/DataPrep/test_data/cog9904_9905_snp6_with_fam" #MODIFY: Prefix for PLINK files containing all of the query samples for ancestry inference
  cog2: "/Users/pmonnaha/Documents/Research/DataPrep/test_data/cog9906_500K_with_fam"
  stjude: "/Users/pmonnaha/Documents/Research/DataPrep/test_data/stjude_500K_with_fam"
#  aall0232: "/home/pmonnaha/shared/data/admiral/aall0232/plink"
#  aric: "/home/pmonnaha/shared/data/admiral/mergeALL_AA/QC_allRaces/aric"
updates:
  chrom_key: "/Users/pmonnaha/Documents/Research/DataPrep/accessory/PlinkChrRename.txt"
  allele_key: "/Users/pmonnaha/Documents/Research/DataPrep/accessory/recodePlinkAlleles.txt"
  ID_key: "/Users/pmonnaha/Documents/Research/DataPrep/accessory/recodePlinkMarkers_noDups.txt"
  FixRef: "true"
QC:
  vm1: "0.2"
  gm: "0.1"
  vm2: "0.02"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.00001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.00001"  # p-value treshold for test of whether missingness varies by sex
reference:
  hg19:
#    vcf: "/home/pmonnaha/pmonnaha/misc/ALL.phase3_shapit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz" #MODIFY: Location of VCF with reference populations
    superpops: "/home/pmonnaha/pmonnaha/misc/ALL.phase3_shapeit2_mvncall_integrated_v5a.20130502.superpopulations.txt"
#    subpops: "accessory/1000G_PopLabels.txt"
#    genmap: "/home/pmonnaha/pmonnaha/accessory/genetic_map_hg19.txt"
    vcf: "/Users/pmonnaha/Documents/Research/1000g/vcf/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    genmap: "/Users/pmonnaha/Documents/Research/hg19/genetic_map_hg19.txt"
    subpops: "/Users/pmonnaha/Documents/Research/1000g/1000G_PopLabels.txt"
bcftools:
  executable: "bcftools"
  threads: '6'
phase:
  ref_pops: "YRI,GWD,ESN,MSL,LWK,CEU,FIN,IBS,TSI" #MODIFY: Reference Populations to include.  Labels for each reference population is specified in pop_names
  threads: "12"
  pbwt_depth: "8"
merge: "true"
dir:
  main: "/home/spectorl/pmonnaha/ancestry/" #CURRENTLY UNUSED
  scratch: "/scratch.global/pmonnaha/"
  out: "/scratch.global/pmonnaha/snakemake_testing/"
  code: "/home/spectorl/pmonnaha/code/"

#plink: "module load plink/1.90b6.10; plink"
#bgzip: "module load htslib/1.6; bgzip"
use_singularity: 'true'
singularity_image: 'AncestryInf.sif'
plink: "plink"
bgzip: "bgzip"
