#Modify all lines indicated with MODIFY
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
outname: "ALL"
local_run: 'false'
query:
  "cog1":
    data: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.genotype-calls-matrixfmt.c1.HMB/with_fam/cog9904_9905_snp6_with_fam"
    chrom_key: "/home/pmonnaha/pmonnaha/misc/PlinkChrRename.txt"
    allele_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/recodePlinkAlleles.txt"
    ID_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/recodePlinkMarkers_noDups.txt"
    flip_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/opposite_strands_ssIDs.txt"
  "cog2":
    data: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.genotype-calls-matrixfmt.c1.HMB/with_fam/cog9906_500K_with_fam"
    chrom_key: "/home/pmonnaha/pmonnaha/misc/PlinkChrRename.txt"
    allele_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/recodePlinkAlleles.txt"
    ID_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/recodePlinkMarkers_noDups.txt"
    flip_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/opposite_strands_ssIDs.txt"
  "stjude":
    data: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.genotype-calls-matrixfmt.c1.HMB/with_fam/stjude_500K_with_fam"
    chrom_key: "/home/pmonnaha/pmonnaha/misc/PlinkChrRename.txt"
    allele_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/recodePlinkAlleles.txt"
    ID_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/recodePlinkMarkers_noDups.txt"
    flip_key: "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.marker-info.c.MULTI/opposite_strands_ssIDs.txt"
  "aall0232":
    data: "/home/pmonnaha/shared/data/admiral/aall0232/plink"
    chrom_key: "/home/pmonnaha/pmonnaha/misc/PlinkChrRename.txt"
    allele_key: "none"
    ID_key: "none"
    flip_key: "none"
  "aric":
    data: "/home/pmonnaha/shared/data/admiral/mergeALL_AA/QC_allRaces/aric"
    chrom_key: "/home/pmonnaha/pmonnaha/misc/PlinkChrRename.txt"
    allele_key: "none"
    ID_key: "none"
    flip_key: "none"
singularity:
  image: '/home/pmonnaha/pmonnaha/singularity/AncestryInference.sif' # MODIFY
  module: 'module load singularity'
  code: 'scripts/'
  use_singularity: 'true'
case_datasets: "aall0232,cog1,cog2,stjude"
control_datasets: "aric"
FixRef: 'true'
download_reference: 'false'
reference:
  refFasta: '/home/pmonnaha/pmonnaha/ALL_DataPrep/RefAnnotationData/human_g1k_v37.fasta.gz'
  refVCF: '/home/pmonnaha/pmonnaha/ALL_DataPrep/RefAnnotationData/All_20170710.vcf.gz'
perform_QC: 'true'
QC:
  vm1: "0.2"
  gm: "0.1"
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.0000001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
impute_prep: 'true'
chroms: "all"
include_x: "no"
bcftools:
  executable: "bcftools"
  threads: '6'
merge: "true"
delete_intermediates: "false"
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
python: 'python3.7'
run_settings:
  local_run: 'false'
  cluster_config: 'workflow/cluster.yaml'
  scheduler: 'pbs'

