#Modify all lines indicated with MODIFY
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
outname: "ALL" #Name that you want to give to any output
build: "37" # Either 37 or 38
query: #!!ONLY USE TEXT AND NUMBERS FOR NAMING DATASETS.  List one or more datasets to be QCed via format demonstrated below.
  "dataset1":
    data: "PATH_TO_PLINK_PREFIX"
    chrom_key: "/home/araduski/araduski/misc/PlinkChrRename.txt" # Used to rename chromosomes to match ref FASTA
    allele_key: "PATH_TO_FILE_WITH_ACGT_SPECIFCATION" # Used for renaming A/B allele specification to ACGT specification (see PLINK documentation for format).  Set to 'none' if data already in ACGT
    ID_key: "PATH_TO_FILE_WITH_rsIDs" #Used to relabel markers with the rsID (see PLINK documentation for format).  Set to 'none' if rsIDs already present
    flip_key: "PATH_TO_FILE_WITH_rsIDs_TO_FLIP" #File with rsIDs to flip.  Typically retrieved from CSV file for array.  Set to 'none' if you are certain that strand is specified correctly.
    pheno_file: "PATH_TO_FILE_WITH_PHENOTYPE_INFO" #If phenotypes are already specified or are not available, set this to 'none'.  Otherwise, format according to PLINK --update-pheno.
    sex_file: "PATH_TO_FILE_WITH_SEX_INFO" #If sexes are already specified or are not available, set this to 'none'. Otherwise, format according to PLINK --update-sex.
  "dataset2":
    data: "PATH_TO_PLINK_PREFIX"
    chrom_key: "/home/araduski/araduski/misc/PlinkChrRename.txt" # Change to "/home/araduski/araduski/misc/PlinkChrRename_hg38.txt" for hg38 build data 
    allele_key: "PATH_TO_FILE_WITH_ACGT_SPECIFCATION" # Used for renaming A/B allele specification to ACGT specification (see PLINK documentation for format).  Set to 'none' if data already in ACGT
    ID_key: "PATH_TO_FILE_WITH_rsIDs" #Used to relabel markers with the rsID (see PLINK documentation for format).  Set to 'none' if rsIDs already present
    flip_key: "PATH_TO_FILE_WITH_rsIDs_TO_FLIP" #File with rsIDs to flip.  Typically retrieved from CSV file for array.  Set to 'none' if you are certain that strand is specified correctly.
    pheno_file: "PATH_TO_FILE_WITH_PHENOTYPE_INFO" #If phenotypes are already specified or are not available, set this to 'none'.  Otherwise, format according to PLINK --update-pheno.
    sex_file: "PATH_TO_FILE_WITH_SEX_INFO" #If sexes are already specified or are not available, set this to 'none'. Otherwise, format according to PLINK --update-sex.
singularity:
  image: '/home/araduski/shared/singularity/AncestryInference.sif' # MODIFY: Path to singularity image file.  The one I used for everything is named AncestryInference.sif, which can be created from scratch using .def file in AncInf repo.
  module: 'module load singularity' #Command that the HPC requires for use of singularity.  Set to empty string if singularity is loaded by default.
  code: 'scripts/' #Path to the scripts directory that was cloned with repo.  Should not need to change this value.
  use_singularity: 'true' #Use a singularity image (i.e. set to true) if possible.  Pipeline has only been tested/debugged with singularity.
FixRef: 'true' #This flag controls whether bcftools +fixref will be run.  That is, should we check positions and alleles for whether they match a specified reference genome.
reference: #Reference files can be provided in one of two ways.  Either provide the paths if you already have the reference files and set download to 'false' -- the paths provided should work for anyone running their analyses on UMN MSI.  Or provide a link that they can be downloaded from and set download to 'true'
  download: 'false' #'true'
  refFasta37: '/home/araduski/araduski/misc/human_g1k_v37.fasta.gz' #'ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz'
  refVCF37: '/home/araduski/araduski/misc/All_20170710.vcf.gz' #'ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170710.vcf.gz'
  refFasta38: '/common/bioref/ensembl/main/Homo_sapiens-110/GRCh38.p14/seq/Homo_sapiens.GRCh38.dna.toplevel.fa.gz'
  refVCF38: '/home/ljmills/and06841/misc/All_20170710.vcf.gz'
perform_QC: 'true'
QC:
  vm1: "0.2" #First pass variant missingness threshold.  Used to remove bad markers prior to identifying high missingness individuals.
  gm: "0.1" #Missingness thresholds for removing individuals.  Applied after vm1 threshold applied to variants.
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.0000001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
  mbc: "0.0001"  # p-value threshold for missingness by case. Note that this is applied to each dataset separately.  Testing subsequent to merging (if requested) must be done manually.
chroms: "all"
include_x: "no"
bcftools:
  executable: "bcftools"
  threads: '6'
  plugins: '/usr/local/bin/miniconda/pkgs/bcftools-1.9-h68d8f2e_9/libexec/bcftools/'
merge: "true"
delete_intermediates: "false"
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
python: 'python'
run_settings:
  local_run: 'false'
  cluster_config: 'workflow/cluster_slurm.yaml'
  scheduler: 'slurm'

