#Modify all lines indicated with MODIFY
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
outname: "test"
local_run: 'true'
query:
#  "cog1": "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.genotype-calls-matrixfmt.c1.HMB/with_fam/cog9904_9905_snp6_with_fam" #MODIFY: Prefix for PLINK files containing all of the query samples for ancestry inference
#  "cog2": "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.genotype-calls-matrixfmt.c1.HMB/with_fam/cog9906_500K_with_fam"
#  "stjude": "/home/pmonnaha/shared/data/admiral/raw/phg000408.v1.NIGMS_ALL_Relapse_GWAS.genotype-calls-matrixfmt.c1.HMB/with_fam/stjude_500K_with_fam"
updates:
  chrom_key: "/home/pmonnaha/pmonnaha/misc/PlinkChrRename.txt"
  allele_key: "none"
  ID_key: "none"
  FixRef: "true"
download_reference: 'true'
reference:
  refFasta: 'none'
  refVCF: 'none'
perform_QC: 'true'
QC:
  vm1: "0.2"
  gm: "0.1"
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.0000001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
impute_prep: 'true'
bcftools:
  executable: "bcftools"
  threads: '6'
merge: "true"
dir:
  main: "/home/spectorl/pmonnaha/ancestry/" #CURRENTLY UNUSED
  scratch: "/scratch.global/pmonnaha/"
  out: "/scratch.global/pmonnaha/snakemake_testing/"
  code: "/home/spectorl/pmonnaha/code/"

plink: "module load plink/1.90b6.10;"
bgzip: "module load htslib/1.6; bgzip"
use_singularity: 'false'
singularity_image: 'AncestryInf.sif'
#plink: "plink"
#bgzip: "bgzip"
