#Modify all lines indicated with MODIFY
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
outname: "cclrp"
local_run: 'false'
query:
  "cclrp": "PATH_TO_PLINK_BED_PREFIX" # MODIFY
singularity:
  image: 'PATH_TO_SIgrep NGULARITY_IMAGE_AncestryInference.sif' # MODIFY
  module: 'module load singularity'
  code: 'scripts/'
  use_singularity: 'true'
case_datasets: ""
control_datasets: ""
updates:
  chrom_key: "scripts/PlinkChrRename.txt"
  allele_key: "none"
  ID_key: "none"
  FixRef: "true"
download_reference: 'true'
reference:
  refFasta: 'none'
  refVCF: 'none'
perform_QC: 'true'
QC:
  vm1: "0.2"
  gm: "0.1"
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.0000001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
impute_prep: 'true'
chroms: "all"
include_x: "no"
bcftools:
  executable: "bcftools"
  threads: '6'
merge: "true"
delete_intermediates: "false"
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
python: 'python3.7'
