#Modify all lines indicated with MODIFY
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
outname: "CCLRP"
local_run: 'false'
query:
  "cclrp": "/PATH/TO/DIRECTORY/CONTAINING/IMPUTATION/OUTPUT/" # MODIFY
phenotype_data: # Must specify a phenotype file where first column is sample ID (must match those in imputed VCFs) and phenotype is second column OR list query datasets by case/control (comma-separated, no spaces)
  pheno_file: "none" #MODIFY
  sex_file: "none" #MODIFY
  case_datasets: "" # e.g. cog1,cog2
  control_datasets: "" # e.g. aric,phg663
singularity:
  image: '/PATH/TO/AncestryInference2.sif' # MODIFY
  module: 'module load singularity'
  code: 'scripts/'
  use_singularity: 'true'
CrossMap:
  exec: "/usr/local/bin/miniconda/bin/CrossMap.py"
  download_refs: 'true'
  chain: "ftp://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh38_to_GRCh37.chain.gz"  #This file must be filtered to exclude any non-canonical chromosome names
  fasta: "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz"
  threads: "6"
min_gp: "0.85"  # Minimum genotype probability.  Values below this are converted to missing.
snp_list: "accessory/ALL_snpLoc.txt"
perform_QC: 'true'
QC:
  vm1: "0.2"
  gm: "0.1"
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.0000001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
chroms: "all"
include_x: "no"
bcftools:
  executable: "bcftools"
  threads: '6'
merge: "false"
delete_intermediates: "false"
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
python: 'python3.7'
