#Modify all lines indicated with MODIFY
outname: "CCRLP"
query:
  "ccrlp": "/PATH/TO/DIRECTORY/CONTAINING/IMPUTATION/OUTPUT/" # MODIFY
phenotype_data: # Must specify a phenotype file where first column is sample ID (must match those in imputed VCFs) and phenotype is second column
  pheno_file: "/PATH/TO/FILE/CONTAINING/PHENOTYPE_DATA" #MODIFY
  sex_file: "/PATH/TO/FILE/CONTAINING/SEX_DATA" #MODIFY
singularity:
  image: '/PATH/TO/SINGULARITY/IMAGE/AncestryInference.sif' # MODIFY
  module: 'module load singularity'
  code: 'scripts/'
  use_singularity: 'true'
CrossMap:
  exec: "/usr/local/bin/miniconda/bin/CrossMap.py" # This will point to the executable installed in the singularity image, and should be left alone if using the associated singularity image
  download_refs: 'true'
  chain: "ftp://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh38_to_GRCh37.chain.gz"  #This file must be filtered to exclude any non-canonical chromosome names
  fasta: "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz"
  threads: "6"
min_gp: "0.85"  # Minimum genotype probability.  Values below this are converted to missing.
snp_list: "accessory/ALL_snpLoc.txt"
perform_QC: 'true'
convert_coords: 'false' # Convert coordinates from hg38 to hg19?
QC:
  Rsq_threshold: "0.5"  # Imputed variants with Rsq less than this threshold will be removed.  Set to 0 to disable filter.
  vm1: "0.2" #First pass variant missingness threshold.  Used to remove bad markers prior to identifying high missingness individuals.
  gm: "0.1" #Missingness thresholds for removing individuals.  Applied after vm1 threshold applied to variants.
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "-9"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
  mbc: "0.0000001"
chroms: "all"
include_x: "no"
bcftools:
  executable: "bcftools"
  threads: '6'
  plugins: '/usr/local/bin/miniconda/pkgs/bcftools-1.9-h68d8f2e_9/libexec/bcftools/'
delete_intermediates: "false"
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
python: 'python'
run_settings:
  local_run: 'false'
  cluster_config: 'workflow/cluster_slurm.yaml'
  scheduler: 'slurm'
